export const CREATE_ESTIMATION_REQUEST = 'CREATE_ESTIMATION_REQUEST'
export const CREATE_ESTIMATION_SUCCESS = 'CREATE_ESTIMATION_SUCCESS'
export const CREATE_ESTIMATION_FAILURE = 'CREATE_ESTIMATION_FAILURE'

export const GET_INPUT = 'GET_INPUT'
