export const CREATE_ESTIMATION_REQUEST = 'CREATE_ESTIMATION_REQUEST'
export const CREATE_ESTIMATION_SUCCESS = 'CREATE_ESTIMATION_SUCCESS'
export const CREATE_ESTIMATION_FAILURE = 'CREATE_ESTIMATION_FAILURE'

export const GET_ESTIMATIONS_REQUEST = 'GET_ESTIMATIONS_REQUEST'
export const GET_ESTIMATIONS_SUCCESS = 'GET_ESTIMATIONS_SUCCESS'
export const GET_ESTIMATIONS_FAILURE = 'GET_ESTIMATIONS_FAILURE'

export const GET_INPUT = 'GET_INPUT'
