export const DISMISS_MESSAGE = 'DISMISS_MESSAGE'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER'
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER'
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER'
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER'
export const LOG_OUT = 'LOG_OUT'

export const SYNC_AUTH = 'SYNC_AUTH'
export const RESTORE_SIGNED_IN_USER_REQUEST = 'RESTORE_SIGNED_IN_USER_REQUEST'
