export const DISMISS_MESSAGE = 'DISMISS_MESSAGE'

export const CREATE_REQUEST = 'CREATE_REQUEST'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER'
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER'
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER'
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER'
export const LOG_OUT = 'LOG_OUT'

export const SYNC_AUTH = 'SYNC_AUTH'
export const RESTORE_SIGNED_IN_USER = 'RESTORE_SIGNED_IN_USER'

export const GET_ESTIMATIONS_REQUEST = 'GET_ESTIMATIONS_REQUEST'
export const GET_ESTIMATIONS_SUCCESS = 'GET_ESTIMATIONS_SUCCESS'
export const GET_ESTIMATIONS_FAILURE = 'GET_ESTIMATIONS_FAILURE'

export const GET_ESTIMATION_REQUEST = 'GET_ESTIMATION_REQUEST'
export const GET_ESTIMATION_SUCCESS = 'GET_ESTIMATION_SUCCESS'
export const GET_ESTIMATION_FAILURE = 'GET_ESTIMATION_FAILURE'

export const CREATE_ESTIMATION_REQUEST = 'CREATE_ESTIMATION_REQUEST'
export const CREATE_ESTIMATION_SUCCESS = 'CREATE_ESTIMATION_SUCCESS'
export const CREATE_ESTIMATION_FAILURE = 'CREATE_ESTIMATION_FAILURE'

export const DELETE_ESTIMATION_REQUEST = 'DELETE_ESTIMATION_REQUEST'
export const DELETE_ESTIMATION_SUCCESS = 'DELETE_ESTIMATION_SUCCESS'
export const DELETE_ESTIMATION_FAILURE = 'DELETE_ESTIMATION_FAILURE'

export const SET_EDIT_DATA = 'SET_EDIT_DATA'
export const RESET_EDIT_DATA = 'RESET_EDIT_DATA'
